<a href="https://colab.research.google.com/github/hzm2000/Studying-pytorch/blob/main/introToCOlap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np


In [8]:
np1 = np.random.rand(3,4)
np1


array([[0.49505684, 0.55230797, 0.0208692 , 0.98606296],
       [0.04579979, 0.85513494, 0.68833809, 0.59922754],
       [0.74734925, 0.2834906 , 0.73936585, 0.05921265]])

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d


tensor([[ 1.0328, -0.0731, -0.4429, -0.7771],
        [ 1.6522,  0.8078,  0.0926,  0.2190],
        [-0.3136,  0.4039, -1.7911,  2.0348]])

In [13]:
tensor_3d = torch.zeros(4,3,5)
tensor_3d

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [14]:
tensor_nump = torch.tensor(np1)
tensor_nump


tensor([[0.4951, 0.5523, 0.0209, 0.9861],
        [0.0458, 0.8551, 0.6883, 0.5992],
        [0.7473, 0.2835, 0.7394, 0.0592]], dtype=torch.float64)